# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - '/tmp/mongodb:/data/db'

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  web:
    build: .
    stdin_open: true
    tty: true
    restart: always
#        command: gunicorn app:app
    volumes:
      - .:/app
    links:
      - "mongo:mongo"
    ports:
      - 80:80
    environment:
      WEB_CONCURRENCY: 2
    depends_on:
      - mongo

  text_builder:
    build:
      context: .
      dockerfile: Dockerfile_text_builder
    stdin_open: true
    tty: true
    restart: always
    command: python3 text_generation.py
    volumes:
      - .:/app
    links:
      - "mongo:mongo"
    depends_on:
      - mongo